-- Engineering-request attachments received from the ERP (BOQ, drawings, specs, photos, layouts).
-- Each item: { category, name, path, url }. url is a short-lived signed link generated by the ERP,
-- because the file lives in the ERP's private storage — EOS only ever holds a link, never the file.
alter table ceks_engineering_requests
  add column if not exists attachments jsonb not null default '[]'::jsonb;

comment on column ceks_engineering_requests.attachments is
  'Supporting files from the ERP engineering request: [{ category, name, path, url }].';
