-- ============================================================================
-- 018 · EQUIPMENT TAXONOMY — complete Family → Category master
--
-- Replaces the initial 4-family seed (migration 016) with the client's authoritative master
-- (EOS_Equipment_Families_and_Categories.xlsx): 11 families, 194 categories.
--   Cooking (31), Refrigeration (28), Food Preparation (30), Warewashing (12), Ice Machines (8), Beverage Equipment (12), Stainless Steel Fabrication (22), Ventilation (11), Bakery Equipment (11), Laundry Equipment (18), Serving & Distribution (11).
--
-- The taxonomy is reference data with no inbound foreign keys, so it is safe to clear and re-seed to
-- match the file exactly. A handful of categories legitimately belong to two families (Deck/Rack/
-- Rotary Oven → Cooking or Bakery; Dough Divider/Rounder/Sheeter, Bread Slicer → Food Prep or Bakery);
-- those categories are stored under BOTH families, and family-derivation treats them as ambiguous
-- (an explicit Family must decide) rather than guessing.
-- Additive migration; idempotent (delete-then-insert produces the same rows on any re-run).
-- ============================================================================

delete from ceks_equipment_taxonomy;

insert into ceks_equipment_taxonomy (family, category, sort_order) values
  ('Cooking', 'Gas Range', 1),
  ('Cooking', 'Wok Range', 2),
  ('Cooking', 'Stock Pot Range', 3),
  ('Cooking', 'Induction Range', 4),
  ('Cooking', 'Solid Top Range', 5),
  ('Cooking', 'Fryer', 6),
  ('Cooking', 'Pasta Cooker', 7),
  ('Cooking', 'Griddle', 8),
  ('Cooking', 'Charbroiler', 9),
  ('Cooking', 'Salamander', 10),
  ('Cooking', 'Bain Marie', 11),
  ('Cooking', 'Hot Plate', 12),
  ('Cooking', 'Bratt Pan', 13),
  ('Cooking', 'Tilting Pan', 14),
  ('Cooking', 'Steam Jacketed Kettle / Boiling Pan', 15),
  ('Cooking', 'Pressure Cooker', 16),
  ('Cooking', 'Combi Oven', 17),
  ('Cooking', 'Convection Oven', 18),
  ('Cooking', 'Deck Oven', 19),
  ('Cooking', 'Pizza Oven', 20),
  ('Cooking', 'Rack Oven', 21),
  ('Cooking', 'Rotary Oven', 22),
  ('Cooking', 'Conveyor Oven', 23),
  ('Cooking', 'Microwave Oven', 24),
  ('Cooking', 'Steamer', 25),
  ('Cooking', 'Rice Cooker', 26),
  ('Cooking', 'Holding Cabinet', 27),
  ('Cooking', 'Heated Holding Cabinet', 28),
  ('Cooking', 'Hot Cupboard', 29),
  ('Cooking', 'Plate Warmer', 30),
  ('Cooking', 'Food Warmer', 31),
  ('Refrigeration', 'Reach-In Refrigerator', 1),
  ('Refrigeration', 'Reach-In Freezer', 2),
  ('Refrigeration', 'Undercounter Refrigerator', 3),
  ('Refrigeration', 'Undercounter Freezer', 4),
  ('Refrigeration', 'Worktop Refrigerator', 5),
  ('Refrigeration', 'Worktop Freezer', 6),
  ('Refrigeration', 'Pizza Preparation Counter', 7),
  ('Refrigeration', 'Salad Preparation Counter', 8),
  ('Refrigeration', 'Sandwich Preparation Counter', 9),
  ('Refrigeration', 'Chef Base Refrigerator', 10),
  ('Refrigeration', 'Chef Base Freezer', 11),
  ('Refrigeration', 'Blast Chiller', 12),
  ('Refrigeration', 'Blast Freezer', 13),
  ('Refrigeration', 'Walk-In Cooler', 14),
  ('Refrigeration', 'Walk-In Freezer', 15),
  ('Refrigeration', 'Display Refrigerator', 16),
  ('Refrigeration', 'Display Freezer', 17),
  ('Refrigeration', 'Cake Display', 18),
  ('Refrigeration', 'Ice Cream Display', 19),
  ('Refrigeration', 'Milk Refrigerator', 20),
  ('Refrigeration', 'Fish Refrigerator', 21),
  ('Refrigeration', 'Meat Aging Cabinet', 22),
  ('Refrigeration', 'Wine Cooler', 23),
  ('Refrigeration', 'Bottle Cooler', 24),
  ('Refrigeration', 'Back Bar Cooler', 25),
  ('Refrigeration', 'Floral Refrigerator', 26),
  ('Refrigeration', 'Pharmacy Refrigerator', 27),
  ('Refrigeration', 'Blood Bank Refrigerator', 28),
  ('Food Preparation', 'Vegetable Cutter', 1),
  ('Food Preparation', 'Food Processor', 2),
  ('Food Preparation', 'Combination Cutter & Mixer', 3),
  ('Food Preparation', 'Planetary Mixer', 4),
  ('Food Preparation', 'Spiral Mixer', 5),
  ('Food Preparation', 'Dough Kneader', 6),
  ('Food Preparation', 'Dough Divider', 7),
  ('Food Preparation', 'Dough Rounder', 8),
  ('Food Preparation', 'Dough Sheeter', 9),
  ('Food Preparation', 'Bread Slicer', 10),
  ('Food Preparation', 'Meat Mincer', 11),
  ('Food Preparation', 'Bone Saw', 12),
  ('Food Preparation', 'Meat Slicer', 13),
  ('Food Preparation', 'Meat Tenderizer', 14),
  ('Food Preparation', 'Sausage Filler', 15),
  ('Food Preparation', 'Hamburger Former', 16),
  ('Food Preparation', 'Potato Peeler', 17),
  ('Food Preparation', 'Vegetable Washer', 18),
  ('Food Preparation', 'Salad Spinner', 19),
  ('Food Preparation', 'Cheese Grater', 20),
  ('Food Preparation', 'Can Opener', 21),
  ('Food Preparation', 'Citrus Juicer', 22),
  ('Food Preparation', 'Juice Extractor', 23),
  ('Food Preparation', 'Bench Blender', 24),
  ('Food Preparation', 'Stick Blender', 25),
  ('Food Preparation', 'Immersion Blender', 26),
  ('Food Preparation', 'Vacuum Packing Machine', 27),
  ('Food Preparation', 'Chamber Vacuum Packing Machine', 28),
  ('Food Preparation', 'Sous-Vide Cooking Tank', 29),
  ('Food Preparation', 'Food Dehydrator', 30),
  ('Warewashing', 'Undercounter Dishwasher', 1),
  ('Warewashing', 'Hood Type Dishwasher', 2),
  ('Warewashing', 'Utensil Washer', 3),
  ('Warewashing', 'Pot Washer', 4),
  ('Warewashing', 'Rack Conveyor Dishwasher', 5),
  ('Warewashing', 'Flight Type Dishwasher', 6),
  ('Warewashing', 'Glasswasher', 7),
  ('Warewashing', 'Tray Washer', 8),
  ('Warewashing', 'Crate Washer', 9),
  ('Warewashing', 'Bin Washer', 10),
  ('Warewashing', 'Waste Bin Washer', 11),
  ('Warewashing', 'Drying Table', 12),
  ('Ice Machines', 'Modular Ice Machine', 1),
  ('Ice Machines', 'Self-Contained Ice Machine', 2),
  ('Ice Machines', 'Ice Dispenser', 3),
  ('Ice Machines', 'Ice Storage Bin', 4),
  ('Ice Machines', 'Cube Ice Machine', 5),
  ('Ice Machines', 'Flake Ice Machine', 6),
  ('Ice Machines', 'Nugget Ice Machine', 7),
  ('Ice Machines', 'Crescent Ice Machine', 8),
  ('Beverage Equipment', 'Espresso Machine', 1),
  ('Beverage Equipment', 'Coffee Machine', 2),
  ('Beverage Equipment', 'Coffee Brewer', 3),
  ('Beverage Equipment', 'Coffee Grinder', 4),
  ('Beverage Equipment', 'Tea Brewer', 5),
  ('Beverage Equipment', 'Hot Water Boiler', 6),
  ('Beverage Equipment', 'Water Boiler', 7),
  ('Beverage Equipment', 'Juice Dispenser', 8),
  ('Beverage Equipment', 'Frozen Beverage Machine', 9),
  ('Beverage Equipment', 'Slush Machine', 10),
  ('Beverage Equipment', 'Milkshake Machine', 11),
  ('Beverage Equipment', 'Beverage Cooler', 12),
  ('Stainless Steel Fabrication', 'Work Table', 1),
  ('Stainless Steel Fabrication', 'Cabinet', 2),
  ('Stainless Steel Fabrication', 'Wall Cabinet', 3),
  ('Stainless Steel Fabrication', 'Base Cabinet', 4),
  ('Stainless Steel Fabrication', 'Sink', 5),
  ('Stainless Steel Fabrication', 'Hand Wash Sink', 6),
  ('Stainless Steel Fabrication', 'Scrub Sink', 7),
  ('Stainless Steel Fabrication', 'Pot Wash Sink', 8),
  ('Stainless Steel Fabrication', 'Shelf', 9),
  ('Stainless Steel Fabrication', 'Wall Shelf', 10),
  ('Stainless Steel Fabrication', 'Rack', 11),
  ('Stainless Steel Fabrication', 'Dunnage Rack', 12),
  ('Stainless Steel Fabrication', 'Trolley', 13),
  ('Stainless Steel Fabrication', 'Tray Trolley', 14),
  ('Stainless Steel Fabrication', 'Ingredient Bin', 15),
  ('Stainless Steel Fabrication', 'Exhaust Hood', 16),
  ('Stainless Steel Fabrication', 'Condensate Hood', 17),
  ('Stainless Steel Fabrication', 'Shelf Over Table', 18),
  ('Stainless Steel Fabrication', 'Pass Shelf', 19),
  ('Stainless Steel Fabrication', 'Grease Trap', 20),
  ('Stainless Steel Fabrication', 'Floor Trough', 21),
  ('Stainless Steel Fabrication', 'Drain Channel', 22),
  ('Ventilation', 'Type I Hood', 1),
  ('Ventilation', 'Type II Hood', 2),
  ('Ventilation', 'UV Hood', 3),
  ('Ventilation', 'Ecology Unit', 4),
  ('Ventilation', 'Fresh Air Unit', 5),
  ('Ventilation', 'Make-Up Air Unit', 6),
  ('Ventilation', 'Exhaust Fan', 7),
  ('Ventilation', 'Supply Fan', 8),
  ('Ventilation', 'Carbon Filter Unit', 9),
  ('Ventilation', 'Odor Control Unit', 10),
  ('Ventilation', 'Fire Suppression System', 11),
  ('Bakery Equipment', 'Dough Divider', 1),
  ('Bakery Equipment', 'Dough Rounder', 2),
  ('Bakery Equipment', 'Dough Sheeter', 3),
  ('Bakery Equipment', 'Dough Moulder', 4),
  ('Bakery Equipment', 'Dough Retarder', 5),
  ('Bakery Equipment', 'Dough Proofer', 6),
  ('Bakery Equipment', 'Rack Oven', 7),
  ('Bakery Equipment', 'Rotary Oven', 8),
  ('Bakery Equipment', 'Deck Oven', 9),
  ('Bakery Equipment', 'Bread Slicer', 10),
  ('Bakery Equipment', 'Cookie Depositor', 11),
  ('Laundry Equipment', 'Washer Extractor', 1),
  ('Laundry Equipment', 'Tumble Dryer', 2),
  ('Laundry Equipment', 'Flatwork Ironer', 3),
  ('Laundry Equipment', 'Roller Ironer', 4),
  ('Laundry Equipment', 'Steam Press', 5),
  ('Laundry Equipment', 'Utility Press', 6),
  ('Laundry Equipment', 'Vacuum Finishing Table', 7),
  ('Laundry Equipment', 'Garment Finisher', 8),
  ('Laundry Equipment', 'Form Finisher', 9),
  ('Laundry Equipment', 'Spotting Table', 10),
  ('Laundry Equipment', 'Laundry Trolley', 11),
  ('Laundry Equipment', 'Food Waste Disposer', 12),
  ('Laundry Equipment', 'Waste Compactor', 13),
  ('Laundry Equipment', 'Garbage Chute', 14),
  ('Laundry Equipment', 'Linen Chute', 15),
  ('Laundry Equipment', 'Waste Bin', 16),
  ('Laundry Equipment', 'Recycling Station', 17),
  ('Laundry Equipment', 'Oil Collection Tank', 18),
  ('Serving & Distribution', 'Heated Trolley', 1),
  ('Serving & Distribution', 'Refrigerated Trolley', 2),
  ('Serving & Distribution', 'Meal Delivery Cart', 3),
  ('Serving & Distribution', 'Plate Dispenser', 4),
  ('Serving & Distribution', 'Tray Dispenser', 5),
  ('Serving & Distribution', 'Tray Conveyor', 6),
  ('Serving & Distribution', 'Buffet Counter', 7),
  ('Serving & Distribution', 'Heated Buffet', 8),
  ('Serving & Distribution', 'Refrigerated Buffet', 9),
  ('Serving & Distribution', 'Mobile Serving Counter', 10),
  ('Serving & Distribution', 'Mobile Banquet Cart', 11)
on conflict (family, category) do nothing;
